# Generated by Django 4.0 on 2022-02-09 06:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name1', models.CharField(max_length=100)),
                ('last_Name1', models.CharField(max_length=100)),
                ('img1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='img1')),
                ('username1', models.CharField(max_length=100)),
                ('Email_id1', models.CharField(max_length=100)),
                ('psw1', models.CharField(max_length=100)),
                ('line_11', models.CharField(max_length=100)),
                ('city1', models.CharField(max_length=100)),
                ('state1', models.CharField(max_length=100)),
                ('pincode1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='img')),
                ('username', models.CharField(max_length=100)),
                ('Email_id', models.CharField(max_length=100)),
                ('psw', models.CharField(max_length=100)),
                ('line_1', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
            ],
        ),
    ]
